---
- name: Deploy Papersocial Website with Docker (RedHat)
  hosts: all
  become: true
  gather_facts: yes

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:

    - name: Install required utilities (RedHat)
      package:
        name: "{{ 'dnf-plugins-core' if ansible_distribution_major_version | int >= 8 else 'yum-utils' }}"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker CE repository (RedHat)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_os_family == 'RedHat'

    - name: Clean yum cache
      command: yum clean all
      when: ansible_os_family == 'RedHat'

    - name: Refresh yum metadata
      command: yum makecache
      when: ansible_os_family == 'RedHat'

    - name: Install Docker packages
      yum:
        name: "{{ docker_packages }}"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python Docker packages
      pip:
        name: 
          - docker
          - docker-compose
        executable: pip3

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: ../website
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
