---
- name: Deploy Papersocial Website with Docker
  hosts: all
  become: true

  tasks:
    - name: Configure Docker CE repositories
      block:
        - name: Install prerequisites (RedHat)
          yum:
            name: yum-utils
            state: present
          when: ansible_os_family == 'RedHat'

        - name: Add Docker CE repository (RedHat)
          yum_repository:
            name: docker-ce
            description: Docker CE Stable
            baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable
            gpgcheck: yes
            gpgkey: https://download.docker.com/linux/centos/gpg
            enabled: yes
          when: ansible_os_family == 'RedHat'

        - name: Install prerequisites (Debian)
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
            state: present
            update_cache: yes
          when: ansible_os_family == 'Debian'

        - name: Add Docker GPG key (Debian)
          apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
            state: present
          when: ansible_os_family == 'Debian'

        - name: Add Docker repository (Debian)
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
            state: present
          when: ansible_os_family == 'Debian'

    - name: Ensure Docker is installed
      package:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python Docker packages
      pip:
        name: 
          - docker
          - docker-compose
        executable: pip3

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: ../website
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
