---
- name: Deploy Papersocial Website with Docker (Ubuntu)
  hosts: all
  become: true
  gather_facts: yes

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update and upgrade all packages
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required system utilities
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Create directory for Docker's GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install build dependencies for Python packages
      apt:
        name:
          - python3-dev
          - libssl-dev
          - libffi-dev
          - build-essential
        state: present

    - name: Install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: true

    - name: Add Docker group
      group:
        name: docker
        state: present

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install python3-docker using apt instead of pip
      apt:
        name:
          - python3-docker
        state: present

    - name: Create build context directory on remote host
      file:
        path: /home/{{ ansible_user }}/build_context
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy website code to build context directory
      copy:
        src: ../website/
        dest: /home/{{ ansible_user }}/build_context/website/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: /home/{{ ansible_user }}/build_context/website/
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
