---
- name: Deploy Papersocial Website with Docker
  hosts: all
  become: true

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:

    - name: Install prerequisites (RedHat)
      yum:
        name: yum-utils
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker CE repository (RedHat)
      ansible.builtin.shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable
      when: ansible_os_family == 'RedHat'

    - name: Import Docker GPG key (RedHat)
      rpm_key:
        state: present
        key: https://download.docker.com/linux/centos/gpg
      when: ansible_os_family == 'RedHat'

    - name: Install Docker packages (RedHat)
      yum:
        name: "{{ docker_packages }}"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install prerequisites (Debian)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key (Debian)
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (Debian)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker packages (Debian)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python Docker packages
      pip:
        name: 
          - docker
          - docker-compose
        executable: pip3

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: ../website
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
