---
- name: Deploy Papersocial Website with Docker
  hosts: all
  become: true

  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python Docker packages
      pip:
        name: docker
        executable: pip3
        extra_args: --break-system-packages

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: ../website
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
