---
- name: Deploy Papersocial Website with Docker
  hosts: all
  become: true

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Website Docker Image
      community.docker.docker_image:
        name: papersocial-web
        build:
          path: ../website
        source: build
        force_source: true
        force_tag: true

    - name: Stop and Remove Existing Container (if any)
      community.docker.docker_container:
        name: papersocial-web
        state: absent
        force_kill: true

    - name: Run Website Container
      community.docker.docker_container:
        name: papersocial-web
        image: papersocial-web
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
