FROM nginx:alpine

LABEL maintainer="kushagraag23@gmail.com"
LABEL description="A containerized static website for my portfolio"
LABEL version="1.0.0"

WORKDIR /usr/share/nginx/html

COPY . /usr/share/nginx/html

EXPOSE 80
