name: Deploy to AWS

on:
  push:
    branches: [master]

env:
  TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Destroy (optional, cleanup before reapply)
        run: terraform -chdir=terraform destroy -auto-approve

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Get EC2 IP
        id: get-ip
        run: |
          echo "IP=$(terraform -chdir=terraform output -raw instance_ip)" >> $GITHUB_OUTPUT

      - name: Configure Ansible Inventory
        run: |
          echo "${{ steps.get-ip.outputs.IP }} ansible_user=ubuntu" > ansible/inventory.ini

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
