name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Get EC2 IP
        id: get-ip
        run: echo "IP=$(terraform -chdir=terraform output -raw instance_ip)" >> $GITHUB_OUTPUT

      - name: Configure Inventory
        run: echo "${{ steps.get-ip.outputs.IP }}" ansible_user=ubuntu > ansible/inventory.ini

      - name: Run Ansible
        uses: ansible/ansible-action@v2
        with:
          playbook: ansible/playbook.yaml
          inventory: ansible/inventory.ini
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
